# Generated by Django 6.0.5 on 2026-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar_project', '0002_remove_chatmessage_likes_chatmessage_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
    ]
